### ISSUE TITLE
some localization entries reference

### ISSUE THREAD

**Issue by claybiockiller** [3TUSK/Temp_LocalizationFile#39]
I have planned to translate Magic Bees mod indepently, but later I found this repository. So I have some idea.
1. "Vazbee" can be translated to “华氏”, so the full name becomes "华氏蜂“ , just a partly transcription and partly translation of original "Vazbee".
2. The word "nickel" may be a pun in description of nickel bee. So “一块镍” in translation text can be changed into "一(五)块(分)镍(钱)".
3. ”Alfheim“ is officially translated as "艾尔夫海姆" officially by Mrkwtkr (same in MCF and Morikawa in MCBBS). So related entries should be changed.

Lastly, please post your localization text as early possible to official repository of Magic Bees mod (github.com/MagicBees/MagicBees) after your work finished.

我原计划独立汉化魔法蜜蜂MOD，但是后来我发现了这个项目。所以我有一些想法：
1. "Vazbee"可译为“华氏”，因此全称就成了“华氏蜂”，正好是"Vazbee"的半音译半意译。
2. 灰镍蜂描述原文中的"nickel"可能是双关语，故汉化文本中的”一块镍“可改为"一(五)块(分)镍(钱)"。
3. ”Alfheim“一词已由Mrkwtr(MCF名相同，MCBBS名为Morikawa)提出官译——"艾尔夫海姆"。 故有关词条应作出相应改变。

最后，请您在汉化完成后尽早将你的汉化文本提交魔法蜜蜂MOD官方(github.com/MagicBees/MagicBees)。

Claybiockiller(Github)/Clayblockiller(MCF)/Clayblock(MCBBS)

**Comment by 3TUSK** [comment]
First, thanks for your time spent on these suggestions on localization of Magic Bees!
One thing need to say first: few weeks ago I have [submitted](https://github.com/MagicBees/MagicBees/pull/61) my zh_CN translation since the previous translation is really out-of-date.
Reply on suggestion:
1.Sounds like a good idea. I will re-open an issue and reference it
2.Ahh I usually use quarter coins... thanks for reminding me and I will review it
3.Localization of "Alfheim" will be synchronized today, I think

Beside, if you feel free and happy you can go ahead and make a pr.

首先，感谢您给出的对魔法蜜蜂本地化的建议！
有一件事情要先说在前面，几周之前我向魔法蜜蜂[提交了](https://github.com/MagicBees/MagicBees/pull/61)zh_CN的本地化文件，因为之前的汉化已经严重过期。
然后是对建议的回复：
1.看上去是一个很好的解决办法。我会把一个相关的issue重新打开并reference这个issue
2.平时我都是在用25分硬币... 感谢提醒，我会重新校对一遍的
3.我想“Alfheim”的本地化今天应该就会同步上来...

另，如果您愿意的话可以直接开一个新的pr...

Best wishes
3TUSK(Github, MCF)/u.s.knowledge(MCBBS)

**Comment by 3TUSK** [comment]
Close this issue without prejudice due to [this pull request](https://github.com/MagicBees/MagicBees/pull/112).
