### ISSUE TITLE
What is "jelly" actually?

### ISSUE THREAD

**Issue by 3TUSK** [3TUSK/Temp_LocalizationFile#58]
According to wikipedia:

> In the U.S. and Canada, jelly refers to a clear or translucent fruit spread made from sweetened fruit (or vegetable) juice and is set by using its naturally occurring pectin

Pretty sure that pam is american. However, jam and jelly _are_ too similar to distinguish. 
Hence we probably need a discussion. I will continue to investigate it, but I also hope someone can leave hint(s) here.
@Ouabain --->This guy changes his/her name every seconds.

**Comment by 3TUSK** [comment]
Okay I found the difference though... jelly _is_ made from juice while jam is from crushed fruit/vegetables. I will leave it open until I made change to my file.

**Comment by Ouabain** [comment]
1. jelly=果冻(注意 冻 这个字)
“a fruit-flavored *dessert* made by warming and then cooling a liquid containing gelatin or a similar setting agent in a mould or dish so that it sets into a semi-soild, some what elastic mass." (chiefly-Brit)

 jam=果酱
制作方法和果冻有所不同,但一般也为凝胶状

2. 我的字典上说美国本地称呼的jelly其实就可以当作jam(可能就是 都是fruit spread?)

3. 我们通常会把jam涂在食物上或者用来制作食物,但很少会用到jelly(注意上面提到的jelly是一种dessert)

所以我的意见就是结合这个东西在pams里的制作方法,使用方法,以及材质上的线索来判断

不过可惜我对这方面不是很熟,给出的解释也并非经过深入研究
你的定义也是对的

**Comment by ghost** [comment]
你的定义是对的,补充几点
1. jelly=果冻(注意 冻 这个字)
   “a fruit-flavored dessert made by warming and then cooling a liquid containing gelatin or a similar setting agent in a mould or dish so that it sets into a semi-soild, some what elastic mass." (chiefly-Brit)
   
   jam=果酱
   制作方法和果冻有所不同,你已经知道了.但一般也为凝胶状
2. 字典上说美国本地称呼的jelly其实就可以当作jam(可能就是 都是fruit spread?)
3. 我们通常会把jam涂在食物上或者用来制作食物,但很少会用到jelly(注意上面提到的jelly是一种dessert)

所以我的意见就是结合这个东西在pams里的制作方法,使用方法,以及材质上的线索来判断

不过可惜我对这方面不是很熟,给出的解释也并非经过研究

**Comment by 3TUSK** [comment]
@Ouabain 根据我经济学老师的说法，（在讲microeconomics的时候）他说peanut butter和jelly是一对complimentary（i.e. 这两种货物一般是需要同时被消费的，也就是说，两者之一的需求量下降都会导致另一种的需求量也下降），然后我想到了Peanut butter and jelly sandwich... 我觉得我有必要周末去一趟walmat看一眼，因为我真心没见过peanut butter and jelly sandwich...

Pam's里的jelly好像是直接用水果+某个工具做出来的。

**Comment by ghost** [comment]
去查了一下,jelly sandwich应该就是指果酱三明治了

它是美国食物加上直接用水果做的话...

**Comment by 3TUSK** [comment]
别的先不说，先安利Peanut butter and jelly sandwith…
然后，jelly大概可以翻译成果酱了…虽然听上去不是那么一回事。
